apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-cicd-ms
spec:
  params:
    - name: apikey
      description: the ibmcloud api key
    - name: branch
      default: master
    - name: triggerEvent
    - name: clusterName
      description: the name of the cluster to target
    - name: clusterTargetNamespace
      default: prod-tkn
  resourcetemplates:
    # CD secret to provide API_KEY to access toolchain information
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: image-to-build
      spec:
        type: image
        params:
          - name: url
            value: "$(params.registryDomain)/$(params.registryNamespace)/$(params.imageName)"
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: the-cluster
      spec:
        type: cluster
        params:
          - name: name
            value: $(params.clusterName)
          - name: username
            value: norealvalueneeded
          - name: url
            value: https://no.real.value.needed
          - name: token
            value: norealvalueneeded
          - name: cadata
            value: norealvalueneeded
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: $(params.branch)-$(params.triggerEvent)-$(uid)
      spec:
        pipelineRef:
          name: pipeline-ms-k8s
        resources:
          - name: app-image
            resourceRef:
              name: image-to-build
          - name: target-cluster
            resourceRef:
              name: the-cluster
        params:
          - name: pipeline-pvc
            value: $(params.branch)-$(params.triggerEvent)-$(uid)-pvc
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-manual
spec:
  params:
    - name: repository
      value: "$(params.manualRepository)"
    - name: branch
      value: "$(params.defaultBranch)"
    - name: triggerEvent
      value: manual
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-github-commit
spec:
  params:
    - name: repository
      value: "$(event.repository.url)"
    - name: revision
      value: "$(event.head_commit.id)"
    - name: branch
      value: "$(params.defaultBranch)"
      # value: "$(event.ref)"
    - name: triggerEvent
      value: "git-commit"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-manual-run
spec:
  triggers:
    - binding:
        name: trigger-binding-manual
      template:
        name: trigger-template-cicd-ms
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-git-commit
spec:
  triggers:
    - binding:
        name: trigger-binding-github-commit
      template:
        name: trigger-template-cicd-ms
