apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-ms-k8s
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    - name: clusterTargetNamespace     
    - name: deploymentFile
      default: deployment.yml
  resources:
  - name: app-image
    type: image
  - name: target-cluster
    type: cluster
  tasks:
    - name: pipeline-1-clone-task
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
    - name: pipeline-2-containerize-task
      runAfter: [pipeline-1-clone-task]
      taskRef:
        name: containerize-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: additionalTags
          value: '1.0.0-dev'
        - name: additionalTagsScript
          value: |
            # Include the clone task output variables in the environment
            source /artifacts/build.properties
            # The script is providing tag(s) as output
            # But logs can be written as error stderr
            echo "Providing an image tag including git branch and commit" >&2
            # Add a specific tag with branch and commit
            echo "1.0.0-${GIT_BRANCH}-${GIT_COMMIT}"
      resources:          
        outputs:
          - name: builtImage
            resource: app-image
    - name: pipeline-3-va-task
      taskRef:
        name: vulnerability-advisor-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: scanReportFile
          value: 'app-image-va-report.json'
        # - name: maxIteration
        #   value: '5'
        # - name: sleepTime
        #   value: '3'
        # - name: failOnScannedIssues          
        #   value: 'false'
      resources:          
        inputs:
          - name: image
            resource: app-image
            from:
              - pipeline-2-containerize-task
    - name: pipeline-4-cluster-setup-task
      taskRef:
        name: fetch-iks-cluster-config
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: clusterPipelineResourcesDirectoryFallback
          value: .tekton-clusters
      resources:          
        inputs:
          - name: cluster
            resource: target-cluster
        outputs:
          - name: cluster
            resource: target-cluster
    - name: pipeline-5-k8s-deployment-validation
      runAfter: [pipeline-2-containerize-task]
      taskRef:
        name: validate-k8s-deployment-file
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: deploymentFile
          value: $(params.deploymentFile)
      resources:          
        inputs:
          - name: image
            resource: app-image
            from:
              - pipeline-2-containerize-task
    - name: pipeline-6-kubernetes-environment-check
      runAfter: [pipeline-4-cluster-setup-task]
      taskRef:
        name: validate-k8s-environment
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: task-pvc-mountpath
          value: /pipelinerun
        - name: clusterPipelineResourcesDirectory
          value: /pipelinerun/.tekton-clusters
        - name: namespace
          value: $(params.clusterTargetNamespace)
      resources:          
        inputs:
          - name: cluster
            resource: target-cluster
          - name: image
            resource: app-image
            from:
              - pipeline-2-containerize-task
    - name: pipeline-7-kubectl-deployment
      runAfter: [pipeline-6-kubernetes-environment-check, pipeline-5-k8s-deployment-validation]
      taskRef:
        name: kubernetes-contextual-execution
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: task-pvc-mountpath
          value: /pipelinerun
        - name: clusterPipelineResourcesDirectory
          value: /pipelinerun/.tekton-clusters
        - name: script
          value: |
            echo "DEPLOYING using manifest"
            set -x
            kubectl apply --namespace $(params.clusterTargetNamespace) -f $(params.deploymentFile)
            set +x
            echo "=========================================================="
            DEPLOYMENT_DOC_INDEX=$(yq read --doc "*" --tojson $(params.deploymentFile) | jq -r 'to_entries | .[] | select(.value.kind | ascii_downcase=="deployment") | .key')
            DEPLOYMENT_NAME=$(yq read --doc ${DEPLOYMENT_DOC_INDEX} $(params.deploymentFile) metadata.name)
            echo -e "CHECKING deployment rollout of ${DEPLOYMENT_NAME}"
            echo ""
            set -x
            if kubectl rollout status deploy/${DEPLOYMENT_NAME} --watch=true --timeout=150s --namespace $(params.clusterTargetNamespace); then
              STATUS="pass"
            else
              STATUS="fail"
            fi
            set +x
            if [ "$STATUS" == "fail" ]; then
              echo "DEPLOYMENT FAILED"
              exit 1
            fi
      resources:          
        inputs:
          - name: cluster
            resource: target-cluster
            from:
              - pipeline-4-cluster-setup-task
